config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :home

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if params[:review_option] == "no_of_lines"
    	get_data  
    else
  	@list_of_files = [CodeReview.find_where_query(session[:file_path]+'/app/views')] rescue []
    end
  end

  def create
  	tmp = params[:files].tempfile
  	destiny_file = File.join(Rails.root.to_s,'public', 'upload_files', params[:files].original_filename)
  	FileUtils.move tmp.path, destiny_file
  	params[:file_path] = destiny_file.split('.').first
  	session[:file_path] = params[:file_path]

  	CodeReview.extract_zip(destiny_file, File.join(Rails.root.to_s,'public', 'upload_files'), destiny_file)
  	get_data 
  	render :index
  end

  # def extract_zip(file, destination, zip_file)
	 #  FileUtils.mkdir_p(destination) if not File.directory?(destination)
	 #  binding.pry
	 #  Zip::File.open(file) do |zip_file|
	 #    zip_file.each do |f|
	 #      fpath = File.join(destination, f.name)
	 #      zip_file.extract(f, fpath) unless File.exist?(fpath)
	 #    end
	 #  end
	 #  File.delete(zip_file)
  # end

  def get_data
  	if params[:get_dir]
  		root_dir = Rails.root.to_s.split("/") - [""]
  		params[:file_path] = "/"+root_dir[0]+"/"+root_dir[1] if not params[:file_path].present?
  		search = params[:file_path]

  		if search.first != "/"
  			search = "/"+search
  		end
		@get_directories = CodeReview.get_list_dir(search) 
  		
	else
	  	if params[:file_path].present? and params[:review_option] == "no_of_lines"
	  		split_file_path = params[:file_path].split('/')
	  		proj_path = split_file_path.last
	  		split_file_path.delete(proj_path)
	  		split_file_path = split_file_path.join('/')
	  		if params[:sub_dir].present? and params[:sub_dir].include?(split_file_path+"/") 
	  			params[:file_path] = (params[:sub_dir].split('/')-[""]).join("/")+proj_path
	  			params[:sub_dir] = []
	  		end
	  		@file_directories = CodeReview.get_list_dir(params[:file_path])
	  	    @file_directories = abc(@file_directories, hash_val=nil, arr=nil)
	  	# @file_directories = @file_directories.group_by(&:keys).map{|k, v| {k.first => v.flat_map(&:values)}}
	  		if params[:sub_dir].present?
	  			@list_of_files = CodeReview.send_root_and_sub_dir(params[:file_path], params[:sub_dir])
	  		end
	  	else
	  		
	  	end
	end

  end

  def abc(act_hash, hash_val=nil, arr=nil)
    hash_val = act_hash if hash_val.nil?
    hash_val.each do |k, v|
	 	if v and v.count > 1
	 	   act_hash[k] = {}
	 		v.each do |val|
	 		  a = act_hash[val]
	 		  act_hash[k][val] = a if a
	 		  act_hash[k] = abc(act_hash[k], nil, arr=nil) if a and a.count > 0
	 		  # act_hash[k][val] = (c ? c : {})
	 		end
	 	end
	 end

	 return act_hash
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1></h1>
<p></p>
<%= form_tag( home_index_path, :multipart => true )do %>
  <%= file_field_tag 'files'   %>
  <%= submit_tag "upload" %>
<% end %>
<% if session[:file_path].present? %>
	<div style="float:bottom">
		<div style="width:30%;float:left">
		<% root_dir = session[:file_path] #Rails.root.to_s.split("/") - [""] %>
		<!-- < %= link_to root_dir[0], root_path(get_dir: true, file_path: "/"+root_dir[0]+"/"+root_dir[1]) %> -->
		<%= link_to "Home", root_path(get_dir: true, file_path: session[:file_path]) %>
		<!-- < % (params[:file_path].split("/") - [""] - [root_dir[0]]).each do |prm| %>
			< % str += "/"+prm %>
			/< %= link_to prm, root_path(get_dir: true, file_path: str) %>
		< % end if params[:file_path].present? %>
		< % @get_directories.first.flatten.each_with_index do |dir, index| %>
		   < %= sub_direct = (dir.split('/') - [root_dir[0]]).join('/') if index == 0 %>
		   < % if index != 0%>
		     &nbsp;&nbsp;&nbsp;
		     < %= link_to dir, root_path(get_dir: true, file_path: params[:file_path]+"/"+dir) %>
		   < % end %>
		   <br/>
		< % end if @get_directories.present? %> -->
		<% j = 0 %>
		<br/>
		</div>
		<div style="width:70%;float:left">
		<%= text_field_tag :abc, params[:file_path].split('/').last, size: "100x100", disabled: true %>
		<%= form_tag root_path,method: :get do %>
		  <%= hidden_field_tag :file_path, params[:file_path], size: "100x100" %>
		  <%= radio_button_tag "review_option", "no_of_lines", ((not params[:review_option].present? or params[:review_option] == "no_of_lines") ? true : false)%>No Of Lines
		   <%= radio_button_tag "review_option", "view_find_query", ((params[:review_option] == "view_find_query") ? true : false) %>Find and Where Query on views
		  <% proj_path = params[:file_path].split('/').last if params[:file_path].present? %>
		  <!-- < %= @file_directories %> -->
		    <!-- < %= print(@file_directories) %> -->
		    <br/>
		  <% @file_directories.each do |k, v| %>
		    <% j += 1 %>
		    <% str = "" %>
		    <% frm_proj_root = (k.split(proj_path)- ["/"] ).last %>
		    <% if not frm_proj_root.include?('public')%>
			    <% data  = frm_proj_root.split('/') %>
			    <% for i in 0..data.length - 2 %>
			    	&nbsp;&nbsp;&nbsp;
			    <% end if j != 1 %>
			    <%= str.to_s %><%= check_box_tag "sub_dir[]", (j == 0 ? params[:file_path].split('/').join('/') : frm_proj_root), ((params[:sub_dir] and params[:sub_dir].include?(frm_proj_root)) ? true : false)%><%= (j == 1 ? proj_path : data.last) %>
		        <br/>
		    <% end %>
		  <% end if @file_directories.present? %>
		  <br/>
		  <%= submit_tag %>
		<% end %>
		</div>
	</div>
	<div style="margin-top:20px"></div>
	<div align="center" style="float:bottom">
		<div style="bg-color:gray">
			<h4 >List of Files</h4>
		</div>
		<div>
			<table style="width:100%">
				<thead>
				    <tr style="width:100%">
				    <% if @list_of_files.present? %>
				    	<th>File Path</th>
				    	<th>Method Name</th>
				    	<th>Line Number</th>
				    	<th>Line count In Method</th>
				   	<% else %>
				   		<th style="width:100%">No record found</th>
				    <%end%>
				    </tr>
				</thead>
			    <% @list_of_files.each do |file|%>
			      <% file.each do |key, val| %>
			        <% if val.present? %>
						<% val.each do |v| %>
						    <tr>
							    <td><%= key.split(root_dir.split('/').last).last %></td>
								<td><%= v[:method_name] %></td>
								<td><%= v[:line_number] %></td>
								<td><%= v[:line_count] %></td>
						    </tr>
						<% end if val.present? %>
					<% end %>
				  <% end if file.present? %>
				<% end if  @list_of_files.present? %>
			</table>
		</div>
	</div>
<% end %>